FROM node:alpine  as stage1
LABEL MAINTAINER "Saravanaprakash Thangavel"
WORKDIR /app
COPY  main.js /app
COPY package.json /app
RUN ["npm","install"]
RUN ls -l

FROM node:alpine
WORKDIR /app
COPY --from=stage1 /app .
EXPOSE 8000
ENTRYPOINT ["npm"]
CMD ["start"]
